spring.application.name=StoryPilot
openai.api.key=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

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/ai
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Connection pool (Hikari - default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=PostgresHikariCP
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000

app.dryRun=false
app.defaultIssueType=Story
debug=true
jira.baseUrl=${JIRA_BASE_URL:https://hakimsingh8439.atlassian.net/}
jira.email=${JIRA_EMAIL:hakimsingh8439@gmail.com}
jira.apiToken=${JIRA_API_TOKEN:ATATT3xFfGF0HhVZYxvL1lmAlu5yZzQ59EJs2wI30gplam9edZSQUOaAYIdfYMhX-DjaLHl9bxaKhoDZwftJqxm6s96TdA2_R7664k7RvAmpJSkYSXu5XH8iLye0UyfqbriTdH_gXhAtnC89KeIgxWcOoLO0tlht-ArpLrG6et38J3JokSXMDv8=D5235904}
jira.projectKey=${JIRA_PROJECT_KEY:SCRUM}